- package-lock.json
- package.json
Running `npm install` once inside the root directory is necessary
> Fix prettier issues

- src/content/pages/industry-solutions/hr/index.en.md
Hinzufügen en-hr-prozesse button ID
> Pst button test 1

- src/content/pages/industry-solutions/hr/index.en.md
- src/content/pages/industry-solutions/marketing/index.en.md
- src/content/pages/industry-solutions/project-management/index.en.md
Optimization Keyword LPs: Marketing, Projektmanagement, HR
> EN Keywordoptimierung Branchen

- src/content/pages/excel-alternative/index.en.md
- src/content/pages/industry-solutions/individual/index.en.md
Keyword optimization LP Workflow EN
> Daniel 15 05

- src/content/posts/202503-cloud-computing/index.en.md
- src/content/posts/20250318-app-erstellen/index.en.md
Keyword optimization Cloud Computing EN
> Daniel 1605

- src/content/posts/marketing-kampagne-planung/index.es.md
> Translation ES

- src/content/posts/20250331-pflanzplan-fruchtfolge-expertentipps-fuer-ihren-garten/index.de.md
> URL Anpassung Blog Planzplan

- src/content/pages/industry-solutions/hr/index.de.md
- src/content/pages/industry-solutions/hr/index.en.md
- src/content/pages/industry-solutions/hr/index.es.md
- src/content/pages/industry-solutions/hr/index.fr.md
- src/content/pages/industry-solutions/hr/index.pt.md
- src/content/pages/industry-solutions/hr/index.ru.md
- src/content/pages/industry-solutions/marketing/index.de.md
- src/content/pages/industry-solutions/marketing/index.en.md
- src/content/pages/industry-solutions/marketing/index.es.md
- src/content/pages/industry-solutions/marketing/index.fr.md
- src/content/pages/industry-solutions/marketing/index.pt.md
- src/content/pages/industry-solutions/marketing/index.ru.md
- src/content/pages/industry-solutions/project-management/index.de.md
- src/content/pages/industry-solutions/project-management/index.en.md
- src/content/pages/industry-solutions/project-management/index.es.md
- src/content/pages/industry-solutions/project-management/index.fr.md
- src/content/pages/industry-solutions/project-management/index.pt.md
- src/content/pages/industry-solutions/project-management/index.ru.md
Integrate Button IDs in Landingpages Marketing, Project Management, HR
> Button_IDs Landingpages

- src/content/posts/20250308-projektmanagement-methoden/index.de.md
- src/content/posts/20250308-projektmanagement-methoden/index.en.md
- src/content/posts/20250308-projektmanagement-methoden/index.fr.md
- src/content/posts/reisekostenabrechnung/index.de.md
- src/content/posts/reisekostenabrechnung/index.en.md
Anpassung Reisekostenabrechnung Title, Description Links DE, EN
> SEO Reisekostenabrechnung

- src/content/pages/airtable-alternative/index.de.md
- src/content/pages/airtable-alternative/index.en.md
- src/content/pages/airtable-alternative/index.es.md
- src/content/pages/excel-alternative/index.en.md
- src/content/pages/excel-alternative/index.es.md
- src/content/pages/industry-solutions/hr/index.en.md
- src/content/pages/industry-solutions/hr/index.es.md
- src/content/pages/industry-solutions/individual/index.en.md
- src/content/pages/industry-solutions/individual/index.es.md
- src/content/pages/industry-solutions/marketing/index.en.md
- src/content/pages/industry-solutions/marketing/index.es.md
- src/content/pages/industry-solutions/project-management/index.en.md
- src/content/pages/industry-solutions/project-management/index.es.md
- src/content/pages/ms-list-alternative/index.de.md
- src/content/pages/ms-list-alternative/index.en.md
- src/content/pages/ms-list-alternative/index.es.md
Anpassung SEO Title and SEO Description.
> SEO Anpassungen  Pages

- src/content/pages/event-management/index.de.md
Hey Daniel, hier einmal die Landing Page Eventplanung als Entwurf zum Check. Die Bilder sind noch Platzhalter. Ich kümmere mich darum, wenn die Struktur passt.
> draft-landing page eventplanung

- src/content/pages/bewerbermanagement/index.de.md
Hallo Daniel, und hier auch noch der Draft für die Landing Page Bewerbermanagement zum Check. Bilder sind wieder nur Platzhalter. Danke!
> draft landing page bewerbermanagement

- src/content/pages/event-management/index.de.md
SEO Anpassungen Eventplanung. Bei den FAQ fehlte eine Frage, die Antwort war aber vorhanden. Ich habe die Frage; "Für wen eignet sich die Eventplanun mit SeaTable?" als Platzhalter eingefügt. Dort fehlt beim Wort Eventplanung das "g" am Ende
> Eventplanung SEO

- src/content/posts/api-optimierung-praxis/index.de.md
- src/content/posts/arbeitszeiterfassung/index.de.md
- src/content/posts/aufgabenverwaltung/index.de.md
- src/content/posts/auslagenerstattung/index.de.md
- src/content/posts/content-ideen/index.de.md
- src/content/posts/content-marketing-strategie/index.de.md
SEO Anpassung an verschiedenen Seiten (Arbeitszeiterfassung, Content Ideen, API Optimierung, aufgabenverwaltung, content marketing strategien
> SEO Optimierung

- src/content/help/app-builder/einstellungen/seitenberechtigungen-in-einer-universellen-app/index.de.md
- src/content/help/app-builder/einstellungen/seitenberechtigungen-in-einer-universellen-app/index.fr.md
- src/content/help/base-editor/ansichten/ansicht-sperren/index.de.md
- src/content/help/base-editor/ansichten/ansicht-sperren/index.en.md
- src/content/help/base-editor/ansichten/ansicht-sperren/index.fr.md
- src/content/help/base-editor/webformulare/webformulare/index.de.md
* Page permissions
* Lock view
* Forms
> Minor improvements (wording, formatting, translations)

- src/content/templates/events/advent-calendar/index.de.md
- src/content/templates/events/attendance-list/index.de.md
- src/content/templates/events/baby-party/index.de.md
- src/content/templates/events/event-management/index.de.md
- src/content/templates/events/festival-planner/index.de.md
- src/content/templates/events/funeral-planner/index.de.md
Anpassung an den Metadaten und tteileweise auch URL Veränderungen an Template Pages der Kategorie Events 1
> Template Pages  SEO Metadaten Events 1

- src/content/templates/events/advent-calendar/index.en.md
- src/content/templates/events/hen-stag-party-planner/index.de.md
- src/content/templates/events/party-planner/index.de.md
- src/content/templates/events/travel-planner/index.de.md
- src/content/templates/events/wedding-planner/index.de.md
- src/content/templates/software-development/bug-tracker/index.de.md
- src/content/templates/software-development/feature-requests/index.de.md
- src/content/templates/software-development/it-helpdesk/index.de.md
- src/content/templates/software-development/product-launch/index.de.md
- src/content/templates/software-development/technology-roadmap/index.de.md
SEO Anpassung an Templatepages: URL, Metadaten, Bilder
> Daniel0708

- src/content/templates/sales/appointment-booking/index.de.md
- src/content/templates/sales/contact-form/index.de.md
- src/content/templates/sales/customer-onboarding/index.de.md
- src/content/templates/sales/order-confirmation/index.de.md
- src/content/templates/sales/quotation-management/index.de.md
SEO Templatepages Sales - Anpassung an URL, Metadaten, Fehlerbehebung Text
> Daniel0708 2

- src/content/pages/finanzplan-erstellen/index.de.md
> Alt Tags Finanzplan erstellen

- src/content/templates/everyday-life/shopping-list/index.de.md
- src/content/templates/everyday-life/shopping-list/index.en.md
- src/content/templates/everyday-life/shopping-list/index.es.md
- src/content/templates/everyday-life/shopping-list/index.fr.md
- src/content/templates/everyday-life/shopping-list/index.pt.md
- src/content/templates/everyday-life/shopping-list/index.ru.md
- src/content/templates/human-resources/recruitment-interviews/index.de.md
- src/content/templates/human-resources/recruitment-interviews/index.en.md
- src/content/templates/human-resources/recruitment-interviews/index.es.md
- src/content/templates/human-resources/recruitment-interviews/index.fr.md
- src/content/templates/human-resources/recruitment-interviews/index.pt.md
- src/content/templates/human-resources/recruitment-interviews/index.ru.md
- src/content/templates/human-resources/shift-schedule/index.de.md
- src/content/templates/human-resources/shift-schedule/index.en.md
- src/content/templates/human-resources/shift-schedule/index.es.md
- src/content/templates/human-resources/shift-schedule/index.fr.md
- src/content/templates/human-resources/shift-schedule/index.pt.md
- src/content/templates/human-resources/shift-schedule/index.ru.md
- src/content/templates/software-development/product-launch/index.en.md
- src/content/templates/software-development/product-launch/index.es.md
- src/content/templates/software-development/product-launch/index.fr.md
- src/content/templates/software-development/product-launch/index.pt.md
- src/content/templates/software-development/product-launch/index.ru.md
/template/product-launch/
/template/recruitment-interviews/
/template/shift-schedule/
/template/shopping-list/
> Template Pages title tag, meta & URL translations

- src/content/templates/events/wedding-planner/index.en.md
- src/content/templates/events/wedding-planner/index.es.md
- src/content/templates/events/wedding-planner/index.fr.md
- src/content/templates/events/wedding-planner/index.pt.md
- src/content/templates/events/wedding-planner/index.ru.md
- src/content/templates/marketing/storyboard/index.de.md
- src/content/templates/marketing/storyboard/index.en.md
- src/content/templates/marketing/storyboard/index.es.md
- src/content/templates/marketing/storyboard/index.fr.md
- src/content/templates/marketing/storyboard/index.pt.md
- src/content/templates/marketing/storyboard/index.ru.md
- src/content/templates/operations/sustainability-management/index.de.md
- src/content/templates/operations/sustainability-management/index.en.md
- src/content/templates/operations/sustainability-management/index.es.md
- src/content/templates/operations/sustainability-management/index.fr.md
- src/content/templates/operations/sustainability-management/index.pt.md
- src/content/templates/operations/sustainability-management/index.ru.md
- src/content/templates/sales/supply-chain-management/index.de.md
- src/content/templates/sales/supply-chain-management/index.en.md
- src/content/templates/sales/supply-chain-management/index.es.md
- src/content/templates/sales/supply-chain-management/index.fr.md
- src/content/templates/sales/supply-chain-management/index.pt.md
- src/content/templates/sales/supply-chain-management/index.ru.md
/template/storyboard/
/template/supply-chain-management/
/template/sustainability-management/
/template/wedding-planner/
> Teplate Pages title tag, meta & URL translations
